--------------------------------------------------------
--  File created - Monday-March-23-2020   
--------------------------------------------------------
DROP SEQUENCE "SPRING"."SEQ_MENU";
DROP TABLE "SPRING"."MENU" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence SEQ_MENU
--------------------------------------------------------

   CREATE SEQUENCE  "SPRING"."SEQ_MENU"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 30 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "SPRING"."MENU" 
   (	"ID" NUMBER, 
	"RESTAURANT" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"TYPE" VARCHAR2(10 BYTE), 
	"TASTE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SPRING.MENU
SET DEFINE OFF;
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (24,'스타동','사케동',8400,'jp','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (1,'두리순대국','순대국',7000,'kr','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (2,'두리순대국','순대국',7000,'kr','hot');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (3,'장터','뚝배기 김치찌게',7000,'kr','hot');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (4,'만리향','간짜장',5000,'ch','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (5,'만리향','짬뽕',6000,'ch','hot');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (6,'짬뽕지존','짬뽕',9000,'ch','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (8,'김남완초밥집','완초밥',13000,'jp','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (9,'김남완초밥집','런치초밥',10000,'jp','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (10,'김남완초밥집','참치도로초밥',33000,'jp','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (11,'진가와','자루소면',8000,'jp','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (12,'진가와','자루소바',9000,'jp','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (13,'백운봉','막국수',9000,'kr','hot');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (14,'대우부대찌게','부대지게',10000,'kr','hot');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (15,'봉된장','열무비빔밥+우렁된장',7000,'kr','hot');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (17,'대우부대찌게','부대찌게',10000,'kr','hot');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (20,'산들애','딸기',500,'kr','hot');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (19,'대우부대찌게','청국장',13000,'kr','mild');
Insert into SPRING.MENU (ID,RESTAURANT,NAME,PRICE,TYPE,TASTE) values (29,'진씨화로','돌솥비빔밥',7000,'kr','mild');
--------------------------------------------------------
--  DDL for Index UQ_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."UQ_MENU" ON "SPRING"."MENU" ("RESTAURANT", "NAME", "TASTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007273
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."SYS_C007273" ON "SPRING"."MENU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "SPRING"."MENU" ADD CONSTRAINT "UQ_MENU" UNIQUE ("RESTAURANT", "NAME", "TASTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SPRING"."MENU" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SPRING"."MENU" MODIFY ("TASTE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MENU" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MENU" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MENU" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MENU" MODIFY ("RESTAURANT" NOT NULL ENABLE);
